### ISSUE TITLE
Rewrite constructors to use "static"?

### ISSUE THREAD

**Issue by hogacz** [brick/date-time#5] opened 2018-04-05 13:06 UTC
http://php.net/manual/en/language.oop5.late-static-bindings.php

Is it possible to use this approach, so if one subclassed your class, constructors are returning also instances of the subclass instead of the original one? Otherwise, subclassing has limited usage.
Example: I wanted to subclass LocalDate to add a very simple "format" method, that will just return "YYYY-mm-dd", but there might be other use cases.

**Comment by BenMorel** [comment] 2018-05-27 19:17
Hi, sorry for the late reply.

I'm not fond of allowing subclassing in my libraries, unless some class is designed specifically for this purpose. Actually, I might even make the classes final at some point, for 2 reasons:

- it adds a constraint for backward compatibility
- I generally find that subclassing a library's classes does not make a good design: instead, if extensibility is required, an interface should be explicitly provided for this purpose; if not, then composition should be favoured over inheritance. 

I'd rather then implement what you think is missing from the library (in this case, a custom format method), so I will close this issue as a duplicate of #3, which is asking for a custom format method as well.

As a final note, did you see that `__toString()` actually returns `YYYY-mm-dd`? So you should be able to use `(string) $date` and be set.

**Closed by BenMorel** 2018-05-27 19:17 UTC
